export const SET_DEPUTY = "SET_DEPUTY";
export const SET_DEPUTIES = "SET_DEPUTIES";
export const SORT_BY_GRADE = "SORT_BY_GRADE";
export const SORT_ALPHABETICALLY = "SORT_ALPHABETICALLY";
export const FILTER_DEPUTIES_BY_GRADE = "FILTER_DEPUTIES_BY_GRADE";
export const SET_EXPANDED_CARD = "SET_EXPANDED_CARD";
